words_api/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from flask_login.utils import login_required
from words_api.forms import UserSignupForm, UserLoginForm
from words_api.models import User, db
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, current_user

auth = Blueprint('auth', __name__, template_folder = 'auth-templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignupForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data 
            username = form.username.data
            password = form.password.data

            user = User(email, username, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {username}', 'user-created')

            login()

            return redirect(url_for('site.home'))

    except:
        raise Exception('Invalid Form Data: Please check your form')
    return render_template('signup.html', form = form)

@auth.route('/login', methods = ['GET', 'POST'])
def login():
    form = UserLoginForm()

    try:
        if request.method =='POST' and form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            session["username"] = form.username.data

            logged_user = User.query.filter(User.username == username).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('Login successful!', 'auth-success')
                return redirect(url_for('site.home'))
            else:
                flash('Your username and/or password is incorrect', 'auth-failed')
                return redirect(url_for('auth.login'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form.')

    return render_template('login.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

words_api/my_words/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from flask_login.utils import login_required
import requests
from words_api.forms import AddWordForm
from words_api.headers import headers
from words_api.models import Word, db

prod = Blueprint("prod", __name__, template_folder="my_words_templates")


@prod.route("/mywords", methods=["GET", "POST"])
@login_required
def mywords():
    username = session["username"]
    form = AddWordForm()

    try:
        if request.method == "POST":
            word = form.word.data
            url = f"https://lingua-robot.p.rapidapi.com/language/v1/entries/en/{word}"
            response = requests.request("GET", url, headers=headers)

            if response.status_code == 200:

                definition = response.json()["entries"][0]["lexemes"][0]["senses"][0][
                    "definition"
                ]
                added_by_user = username

                entry = Word(word, definition, added_by_user)

                db.session.add(entry)
                db.session.commit()

                flash(
                    f"{word.title()} added to {added_by_user}'s word list. {word.title()}: {definition}",
                    "user-created",
                )
            else:
                flash(
                    f"The word '{word.title()}' did not appear in our search. Please check the spelling of the word you entered or try another word."
                )

    except:
        # raise Exception('Invalid Form Data: Please check your form')
        flash(
            f"The word '{word}' did not appear in our search. Please check the spelling of the word you entered or try another word."
        )

    return render_template("mywords.html", form=form)

words_api/site/routes.py
from flask import Blueprint, render_template, session, flash, request, redirect, url_for
from flask_login.utils import login_required
from words_api.models import User, db
from words_api.forms import UpdateEmail

site = Blueprint('site', __name__, template_folder = 'site-templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    print(session)
    id = session["_user_id"]
    user = User.query.get(id)
    nameEmail = [user.username, user.email]
    return render_template('profile.html', data=nameEmail)
    # return render_template('profile.html')

@site.route('/update_email', methods = ['GET', 'POST'])
@login_required
def update_email():
    id = session["_user_id"]
    user = User.query.get(id)
    children_list = [element for element in user.children.all()]
    form = UpdateEmail()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            user.email = form.email.data
            db.session.commit()
            flash(f'Your email address has been updated to {user.email} 🙂', 'user-created')
            return redirect(url_for('site.home'))

    except:
        raise Exception('Invalid Form Data: Please check your form')

    return render_template('update_email.html', form = form)

# @site.route('/update_email/<id>', methods = ['GET', 'PUT'])
# def update_email(id):
#     username = session["username"]
#     form = UpdateEmail()
#     my_data = User.query.get(id)
#     my_data.email = form.email.data
#     db.session.commit()
#     flash(f'Email address successfully updated for {username}')

words_api/templates/addword.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="word-field">
            {{ form.word.label }}
            {{ form.word(class = "form-control", placeholder = "Enter a word here to add to your words!") }}
        </fieldset>
        {{ form.submit_button(class = "btn btn-success btn-block") }}
    </div>
</form>

words_api/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="static/css/main.css">
<title>{% block title %} {% endblock %}</title>
</head>
<body>

    <ul class="nav justify-content-end">
        <li class="nav-item">
            <a class="nav-link" href ="{{ url_for('site.home') }}">
                <p>Homepage</p>
            </a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href ="{{ url_for('prod.mywords') }}">
            <p>My Words 📑</p>
        </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href ="{{ url_for('display.displaywords') }}">
            <p>Display My Words 📑</p>
        </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href ="{{ url_for('site.profile') }}">
            <p>View My Profile</p>
        </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href ="{{ url_for('auth.logout') }}">
                <p>Log Out</p>
            </a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href = "{{ url_for('auth.login') }}">
                <p>Log In</p>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href = "{{ url_for('auth.signup') }}">
                <p>Sign Up for Free!</p>
            </a>
        </li>            
        {% endif %}
      </ul>
    {% block content %} {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

words_api/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Enter a Username Here!") }}
        </fieldset>
        <fieldset id ="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Enter a Password Here!") }}
        </fieldset>

        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>

words_api/templates/loginform.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Enter a Username Here!") }}
        </fieldset>
        <fieldset id ="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Enter a Password Here!") }}
        </fieldset>

        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>

words_api/templates/signupform.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Enter an email address here!")}}
        </fieldset>
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Enter a Username Here!") }}
        </fieldset>
        <fieldset id ="password-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Enter a Password Here!") }}
        </fieldset>

        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>